# -*- coding: utf-8 -*-
"""interpolation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n2qXsb-cweh7CAFx9YefGwwNL8VOmO8C
"""

import numpy as np
import math
from matplotlib import pyplot as plt

# sampling rate = 60kHz
sr = 60000
t = np.linspace(0,1,20*sr)
ts = np.linspace(0,1,sr)
T = 1/sr
f = 10000
# Signal x(t)
x   = np.cos(2*np.pi*f*t)
# signal x(1+t/2)
x1 = np.cos(2*np.pi*f*(1+(t/2)))
# signal y(t)
y = x*x1

# Signal x(t)
xs   = np.cos(2*np.pi*f*ts)
# signal x(1+t/2)
x1s = np.cos(2*np.pi*f*(1+(ts/2)))
# signal y(t)
ys = xs*x1s


n = 0
interpolate = 0
for n in range(len(ts)):
  interpolate = interpolate + ys[n]*np.sinc((t-n*T)/T)

plt.plot(t[0:2000],y[0:2000],marker='*')

plt.stem(ts[0:100],ys[0:100])
plt.plot(t[0:2000],interpolate[0:2000],color='g')

for n in range(len(ts)):
  print(n)