# -*- coding: utf-8 -*-
"""Gate_Assignment_3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gCPcWDLbQuvNdI1JJFPCPjfamI4KDg3t
"""

import numpy as np
from matplotlib import pyplot as plt
from scipy.signal import unit_impulse

x_n = (1/2)*unit_impulse(5)+unit_impulse(5,1)+2*unit_impulse(5,2)+unit_impulse(5,3)+(1/2)*unit_impulse(5,4)
y_n = (1/2)*unit_impulse(9)+unit_impulse(9,2)+2*unit_impulse(9,4)+unit_impulse(9,6)+(1/2)*unit_impulse(9,8)

#Plotting for the figures given in question
plt.stem(np.arange(-2,3),x_n,use_line_collection=True)
plt.xlabel('$n$')
plt.ylabel('$x(n)$')
plt.grid()
plt.show()

#Option a
plt.stem(np.arange(-2,7),y_n,use_line_collection=True)
plt.xlabel('$n$')
plt.ylabel('$y(n)$')
plt.grid()
plt.show()

#Option b
plt.stem(np.arange(-3,6),y_n,use_line_collection=True)
plt.xlabel('$n$')
plt.ylabel('$y(n)$')
plt.grid()
plt.show()

#Option c
plt.stem(np.arange(-3,6)-3,y_n,use_line_collection=True)
plt.xlabel('$n$')
plt.ylabel('$y(n)$')
plt.grid()
plt.show()

#Option d
plt.stem(np.arange(-3,6)-2,y_n,use_line_collection=True)
plt.xlabel('$n$')
plt.ylabel('$y(n)$')
plt.grid()
plt.show()

#Plotting subplots for the solution
plt.subplot(2, 1, 1)
plt.stem(np.arange(-2,3),x_n,use_line_collection=True)
plt.ylabel('$x(n)$')
plt.grid()

plt.subplot(2, 1, 2)
plt.stem(np.arange(-2,7),y_n,use_line_collection=True)
plt.xlabel('$n$')
plt.ylabel('$y(n)$')
plt.grid()
plt.show()