# -*- coding: utf-8 -*-
"""Gate2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MMr0H7tigjVlN-7TYF8rhJg75gvXTdu8
"""

import numpy as np
from matplotlib import pyplot as plt

time = np.linspace(-3,5,10000)
e2 = np.exp(-2*time)
e1 = np.exp(-1*time)
e3 = np.exp(-3*time)
def unit(time):
  x=[]
  for i in time:
    if i<0:
      x.append(0)
    else:
      x.append(1)
  return x      
x = e2*unit(time)
y = (e1-e3)*unit(time)
plt.plot(time,x,label='x(t)')
plt.plot(time,y,label='y(t)')
plt.xlabel('Time')
plt.grid()
plt.legend()