# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VemN2RYybVYwmN0TfgSvDf5_0SYIeYX_
"""

import numpy as np
import matplotlib.pyplot as plt
from numpy import abs

def rect(x):
    if (abs(x)<=0.5):
        return 1
    elif (abs(x) == 0.5):
      return 1/2     
    else:
       return 0

X = np.linspace(-2,2,1000000)

Y = [rect(x/2) for x in X]
plt.xlabel('t')
plt.ylabel('$x(t)=rect(x/2)$')
plt.plot(X,Y)
plt.grid()
plt.show()